version: 2.4.4
jobs:
  check:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx4096m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "testing-ktx/build.gradle" }}
      - run:
          name: Get Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "testing-ktx/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew check
      - store_artifacts:
          path: testing/build/reports
          destination: testing/reports
      - store_artifacts:
          path: testing-ktx/build/reports
          destination: testing-ktx/reports
      - store_test_results:
          path: testing/build/test-results
      - store_test_results:
          path: testing-ktx/build/test-results
  deploy:
    environment:
      _JAVA_OPTIONS: "-Xmx4g"
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "testing-ktx/build.gradle" }}
      - run:
          name: Deploy Bintray Artifacts
          command: ./gradlew bintrayUpload -Pbintray.user=$BINTRAY_USER -Pbintray.apikey=$BINTRAY_APIKEY
workflows:
  version: 2
  workflow:
    jobs:
      - check:
          filters:  # required since `deploy` has tag filters AND requires `check` https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
            tags:
              only: /.*/
      - deploy:
          requires:
            - check
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]{1,}.[0-9]{1,}.[0-9]{1,}/

