name: Build
on: [push]
env:
  JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Run Tests
        run: ./gradlew check --stacktrace
