name: Release To Maven Central
on:
  release:
    types: [published]
env:
  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
  SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
  JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Publish Release
        run: ./gradlew publishReleasePublicationToSonatypeRepository --stacktrace
